apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: employeereplicaset
  labels:
    app: employee
spec:
  replicas: 3
  selector:
    matchLabels:
        app: employee

  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        ports:
          - containerPort: 8080
            protocol: TCP
        image: 402242685480.dkr.ecr.us-east-1.amazonaws.com/app:v.01
        env:
        - name: DBHOST
          value: mysqlservice.sql.svc.cluster.local  
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw 
        - name: DATABASE
          value: employee
        - name: DBPORT
          value: "3306"
        - name: APP_COLOR
          value: pink
      imagePullSecrets:
        - name: secret-registry