apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
        app: mysql
  template:
    metadata:
      labels:
          app: mysql
    spec:
      containers:
      - name: mysql
        image: 402242685480.dkr.ecr.us-east-1.amazonaws.com/sql:v.01
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pw
          - name: MYSQL_DATABASE
            value: employee
        ports:
        - containerPort: 3306
          protocol: TCP
      imagePullSecrets:
        - name: secret-registry
