apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 402242685480.dkr.ecr.us-east-1.amazonaws.com/sql:v.01
      env:
          - name: MYSQL_ROOT_PASSWORD
            value: pw
          - name: MYSQL_DATABASE
            value: employee
      ports:
        - containerPort: 3306
          protocol: TCP 

  imagePullSecrets:
    - name: secret-registry